### ISSUE TITLE
call to action + link for empty idea list in refinement phase and wild ideas

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#866] opened 2016-07-18 10:29 UTC
If there are no ideas in the list view of the wild ideas or the refinement phase, we currently show „Keine Ideen“. We should add a link to create a new idea to this labelled „Erstelle <a href="<URL>">hier</a> eine neue Idee.“

**Comment by fisx** [comment] 2016-07-18 11:30
duplicate of #832.  (#832 fixes related issues, too.)

**Closed by fisx** 2016-07-18 11:30 UTC

**Comment by fisx** [comment] 2016-07-18 11:32
(fixed reference in last comment.  it's #823.  sorry.)
