### ISSUE TITLE
Markdown fields escape HTML

### ISSUE THREAD

**Issue by localgrr** [liqd/aula#469] opened 2016-05-10 16:15 UTC
I think i confirmed that the backend is making EG ```<haskell> in to &lt;haskell&gt;```

**Comment by fisx** [comment] 2016-05-10 16:27
ok, that's easy to fix, but it has tricky consequences.  do we want users to be able to inject html into other user's browsers?

I would be more comfortable with leaving it as is, but if we need to change it, I would want to look into how we can make it at least reasonably secure.

Either way, good catch.  Thanks for reporting it!

**Comment by fisx** [comment] 2016-05-11 12:47
@localgrr how do i reproduce this?

![2016-05-11-144536_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15181374/26ccb5e4-1787-11e6-93e7-c4030c081135.png)
![2016-05-11-144541_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15181378/2c422874-1787-11e6-904b-8954d3cc447a.png)

**Comment by localgrr** [comment] 2016-05-11 13:19
@fisx not sure what you mean ? It just seems to do that

**Comment by fisx** [comment] 2016-05-11 14:00
Summary of off-line discussion:

- we both can't reproduce the issue, neither in idea descriptions (markdown) nor in topic descriptions (plaintext, at least for the moment, i still think it should also be markdown).
- in plaintext, if we enter `&lt;`, the text is rendered correctly, but on going back into edit mode, it is transformed into `<`.

I will investigate the latter now.

**Comment by fisx** [comment] 2016-05-11 14:00
Summary of off-line discussion:

- we both can't reproduce the issue, neither in idea descriptions (markdown) nor in topic descriptions (plaintext, at least for the moment, i still think it should also be markdown).
- in plaintext, if we enter `&lt;`, the text is rendered correctly, but on going back into edit mode, it is transformed into `<`.

I will investigate the latter now.

**Comment by fisx** [comment] 2016-05-11 14:01
Summary of off-line discussion:

- we both can't reproduce the issue, neither in idea descriptions (markdown) nor in topic descriptions (plaintext, at least for the moment, i still think it should also be markdown).
- in plaintext, if we enter `&lt;`, the text is rendered correctly, but on going back into edit mode, it is transformed into `<`.

I will investigate the latter now.

**Comment by fisx** [comment] 2016-05-12 04:33
ah, the undesired escaping only happens in code blocks.

**Comment by fisx** [comment] 2016-05-18 10:13
See also: https://github.com/showdownjs/showdown/wiki/Showdown%27s-Markdown-syntax

**Comment by np** [comment] 2016-05-19 07:52
So here is what I can reproduce on https://aula-stage.liqd.net/space/2016-12b/idea/3435/view/#auid-5939 namely version 0.11.1.

For instance writing `` `<` `` (backtick, leftangle, backtick), produces the html entity: `&lt;`.

**Comment by fisx** [comment] 2016-05-19 15:25
ok, i can reproduce that, too.  thanks!

**Comment by fisx** [comment] 2016-05-30 13:25
i finally got what happens here!

showdown expects its contents to contain html snippets (which is legal in markdown).  it then escapes those html snippets that are marked as code (see https://github.com/showdownjs/showdown/issues/17).

since aula doesn't want html code to be injected, it escapes them on the server side.  that leads to the behavior intended by us, but surprising to showdown, namely that html code will be displayed verbatim even outside code blocks.  and it leads to the double-escape.

so what should we do?  i don't want to allow arbitrary html because that includes `<script>`.

**Comment by fisx** [comment] 2016-05-30 13:44
related: http://stackoverflow.com/questions/1637275/simple-html-sanitizer-in-javascript

**Comment by fisx** [comment] 2016-05-30 13:58
even more helpful:
- https://github.com/google/caja/wiki/CajaWhitelists
- https://github.com/google/caja/blob/4e77c97a344f2e296294d1f1d7c321cf23362edb/src/com/google/caja/lang/html/html5-elements-whitelist.json
- https://github.com/google/caja/blob/4e77c97a344f2e296294d1f1d7c321cf23362edb/src/com/google/caja/lang/html/html5-attributes-whitelist.json
- https://github.com/google/caja/blob/4e77c97a344f2e296294d1f1d7c321cf23362edb/src/com/google/caja/lang/css/css3-whitelist.json

**Comment by fisx** [comment] 2016-05-30 13:59
so i guess a heavy-weight solution would be to receive the html code on the server side and then scrub it with the above "whitelists".  (why do whitelists have deny clauses?)

**Comment by fisx** [comment] 2016-05-30 14:44
i think the deny clauses are just there for documentation purposes.

so here is the plan:

1. read the white lists at start time.
1. tokenize markdown text during form processing using http://hackage.haskell.org/package/html-parse
1. sieve all tokens through the whitelists and construct a list of offending elements, attributes, and css properties.
1. if the list is non-empty, fail the form with a list of errors (one for each offence).
1. if the list is empty, construct a `Document`.

all steps except 1. can be hidden in a smart constructor, and `Document` can be made an abstract type that should probably move to a new module with all the rest of this.

**Closed** 2016-06-03 14:53 UTC
