### ISSUE TITLE
Default text for missing delegations

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#857] opened 2016-07-18 10:13 UTC
There should be a nice centered text message „Es sind keine Beauftragungen vorhanden“ when there are not delegations to show in the respective tabs user profiles and topic overview (just as we do it, when there are no ideas to show)
https://aula-stage2.liqd.net/user/10/delegations/to

**Comment by fisx** [comment] 2016-07-18 11:38
duplicate of #823.

**Closed by fisx** 2016-07-18 11:38 UTC
