### ISSUE TITLE
Show icons for feasible/non-feasible ideas

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#509] opened 2016-05-18 09:36 UTC
Jury phase: Ideas marked as feasible or not feasible should indicate that status via an icon on the idea detail page and in the topic overview (see here: https://marvelapp.com/ehhb43#10111787) [FIXED in v0.7.0, needs design tweaking]

**Comment by fisx** [comment] 2016-05-18 09:44
probably a duplicate of #508?  i'll leave both open because they contain different pieces of info.

**Comment by fisx** [comment] 2016-05-23 11:17
Related: #519, #498.

**Comment by localgrr** [comment] 2016-05-24 13:01
I feel like this is closed now, cant remember by what...

**Comment by fisx** [comment] 2016-05-24 13:20
This is what it looks like now:

- more padding against the vote bar?
- check / cross symbol should either replace or complement the "durchführbar" or "nicht durchführbar"
- not sure about the gray background.  I think i stole that from somewhere.

![2016-05-24-151751_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15505217/ce45aa7a-21c2-11e6-96a7-36523c4f22f9.png)

**Comment by localgrr** [comment] 2016-05-24 13:30
Oops sorry I'd misunderstood on it now...

**Closed** 2016-05-24 14:58 UTC
