### ISSUE TITLE
topic overview: implement filter for all categories

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#650] opened 2016-06-13 11:58 UTC
To make its workings more obvious Marina wants us to implement an a filter called “all categories (label in German “alle”) on the topic overview: https://aula-stage.liqd.net/space/school/ideas. It should be selected by default and it should also show ideas from all categories when you click on it after selecting. Nadine made an icon for this (you can find it attached – I can provide the SVG via email).

![all_categories_x2](https://cloud.githubusercontent.com/assets/15341015/16006704/c20dc268-316e-11e6-84fb-854ad5527318.png)
![all_categories](https://cloud.githubusercontent.com/assets/15341015/16006705/c2327734-316e-11e6-9333-a8b713bce89a.png)

**Comment by fisx** [comment] 2016-06-13 15:49
duplicate of #607.

**Closed** 2016-06-20 11:06 UTC
