### ISSUE TITLE
Add a category filter for “all”

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#607] opened 2016-05-29 21:13 UTC
We should add a category icon that is active by default and says “alle”, which indicates that currently all categories are active. It might be a bit more expressive also if a user wants to disable the filter. I will ask Nadine for an appropriate icon.

<img width="664" alt="bildschirmfoto 2016-05-29 um 23 11 40" src="https://cloud.githubusercontent.com/assets/15341015/15636044/fe171cdc-25f2-11e6-8581-3a11a32159b5.png">

**Comment by fisx** [comment] 2016-06-13 15:50
duplicate of #650

**Closed by fisx** 2016-06-13 15:50 UTC
